### PR TITLE
Fix scala console212

### LINKED ISSUE #196: scala:console crashes with scala 2.12.0
Scala console crashes shortly after starting up for a project depending on scala 2.12.0:
```
/t/tmpsh.64445 ▶ mvn scala:console
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building test NEXT-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:console (default-cli) @ test ---
[WARNING] scala-maven-plugin cannot fork scala console!!  Running in process
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.101 s
[INFO] Finished at: 2016-11-16T18:46:39+03:00
[INFO] Final Memory: 49M/597M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:console (default-cli) on project test: wrap: java.lang.reflect.InvocationTargetException: jline.console.completer.CandidateListCompletionHandler.setPrintSpaceAfterFullCompletion(Z)V -> [Help 1]
…
```
Here's what POM looks like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <version>NEXT-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.12.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>3.2.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                            <goal>add-source</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
When scala version is set to 2.11.8, the consle works fine. I've also attached the [output](https://github.com/davidB/scala-maven-plugin/files/596892/maven-output.txt)
 of `mvn -X scala:console`. I'm not quite sure this is the plugin's issue, but the standalone scala console works fine for me.

### PR DESCRIPTION
**Pull request by isomarcte**
Derive the JLine dependency from the Scala compiler. This fixes #196 and allows use of `scala:console` with scala 2.12.

**Important**, this PR requires the changes introduced in #205. That PR should be reviewed first. If there are changes made as a result of the review of #205, I'll port them into this PR if/when that PR is merged.

Closes #196 

* `src/main/java/scala_maven/ScalaMojoSupport.java`
  * Added `static` values for a couple `String` values used internally in the
    class, namely "pom" and "jar". Updated usage instances of strings in the
    class to use the constants.
  * Added method to resolve the `Artifact` for the `scala-compiler`.
  * Added more general overloads for `resolveDependencyArtifacts` allowing for
    specification of various artifact filters. Changed the resolution method to
    use the non-deprecated `ArtifactResolutionRequest` type. This is the only
    non-deprecated way to resolve `Artifacts` in Maven as of now.
  * Added an overloaded variant of the `getScalaCommand` which allows
    specification the following behaviors.
    * `forkOverride` - Whether or not to `fork` regardless of the setting in the
      plugin. This currently is only used (and is in fact required) by the
      `scala:console` goal.
    * `mainClass` The JVM class to invoke as main. This currently only has
      use (and is in fact required) by the `scala:console` goal.
  * Added overloaded variant of `getEmptyScalaCommand` that also allows the same
    `forkOverride` behavior seen in `getScalaCommand`. As the former method
    delegates to this one.
  * Updated call to `resolveDependencyArtifacts` to use the
    `resolveArtifactDependencies` operating on the `Artifact` rather than the
    `MavenProject`.
* `src/main/java/scala_maven/ScalaConsoleMojo.java`
  * Added `static` values for a couple `String` values used internally in the
    class, namely "jline" and "org.scala-lang".
  * Updated the `doExecute` method to use the `JavaMainCaller`.
  * Added several `private` methods to choose the correct `jline` dependency
    based on the `scala-compiler` artifact version and dependencies as well as a
    few that just perform general cleanup.
    * `handleJavaRebel` - This method adds the Java Rebel setup if it
      `javaRebelPath` is non-null and the target path exists. The logic this
      method performs is unchanged it was merely factored out into an isolated
      `private` method to reduce noise in the `doExecute` method.
    * `setupClassPathForConsole` - This is the top level `private` method for
      constructing the correct classpath for use with the scala console. It
      merely takes the project classpath and merges it with required console
      classpath.
    * `setupProjectClasspaths` - This method adds the scal compiler and standard
      library to the classpath. It also conditionally adds test classpath and
      runtime classpath.
    * `setupConsoleClasspaths` - Adds any console specific artifacts to the
      classpath. Currently this is just JLine.
    * `resolveJLine` - This method attempts to derive the correct
      JLine dependency to use by finding the version used as an optional
      dependency by the `scala-compiler` artifact at the given version, falling
      back to the hard coded constants that were in use prior to this commit if
      it is unable to resolve the Jline version. Note, I have not found any case
      where it does _fail_ and fallback, but I've left it in here just _in
      case_.
    * `filterForJline` - Filter predicate that is applied to the dependencies on
      the `scala-compiler` to find the JLine dependency.
    * `fallbackJLine` - Fallback constant hard coded values for JLine which are
      only used if we can not derive the correct version from the
      `scala-compiler` artifact.

### CODE REVIEW

**Comment by davidB** [comment]
I merge #205 .

**Comment by isomarcte** [comment]
@davidB I rebased this PR. It is good to go at your discretion.

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 1]
```diff
@@ -55,50 +75,263 @@
...
+            super.scalaCompilerArtifact(scalaVersion.toString());
+        final Set<Artifact> compilerDeps =
+            super.resolveArtifactDependencies(compilerArtifact);
+        for (final Artifact a : compilerDeps) {
+            super.getLog().warn(a.toString());
+            if (this.filterForJline(a)) {
+                return a;
             } else {
-                jcmd.addJvmArgs("-noverify", "-javaagent:" + javaRebelPath.getCanonicalPath());
+                continue;
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: the else clause could be removed ?

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 2]
```diff
@@ -55,50 +75,263 @@
...
+     */
+    private Artifact fallbackJLine(final VersionNumber scalaVersion) {
+        // https://github.com/scala/scala/blob/365ac035a863a666f86151371db77c6d401e88a2/versions.properties#L29
+        final VersionNumber scala2_12_0M4 =
+            new VersionNumber("2.12.0-M4");
+        final VersionNumber scala2_11_0 =
+            new VersionNumber("2.11.0");
+        final VersionNumber scala2_9_0 =
+            new VersionNumber("2.9.0");
+
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: one line per final

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 3]
```diff
@@ -55,50 +75,263 @@
...
+     *
+     * @return A {@link Set} of {@link String} of the classpath as defined by
+     *
+     * @throws {@link Exception} for many reasons, mostly relating to ad-hoc
+     *         dependency resolution.
+     */
+    private Set<String> setupConsoleClasspaths(final VersionNumber scalaVersion) throws Exception {
+        final Set<String> classpath =
+            new HashSet<String>();
+
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: on one line

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 4]
```diff
@@ -55,50 +75,263 @@
...
+     * @return A {@link Set} of {@link String} defining the classpath for the
+     *         project and plugin settings.
+     *
+     * @throws {@link Exception} for many reasons, mostly relating to ad-hoc
+     *         dependency resolution.
+     */
+    private Set<String> setupProjectClasspaths() throws Exception {
+        final Set<String> classpath =
+            new HashSet<String>();
+
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: on one line

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 5]
```diff
@@ -55,50 +75,263 @@
...
+     * @return A {@link Set} of {@link String} defining classpath values to
+     *         provide to the Scala console.
+     *
+     * @throws {@link Exception} for many reasons, mostly relating to ad-hoc
+     *         dependency resolution.
+     */
+    private Set<String> setupClassPathForConsole(final VersionNumber scalaVersion) throws Exception {
+        final Set<String> classpath =
+            new HashSet<String>();
+
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: on one line

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 6]
```diff
@@ -55,50 +75,263 @@
...
+     * If we are unable to find it or {@link #javaRebelPath} is {@code null},
+     * then nothing is done to the given {@link JavaMainCaller}.
+     *
+     * @param jcmd the {@link JavaMainCaller} to which to add the JRebel settings.
+     */
+    private void handleJavaRebel(final JavaMainCaller jcmd) throws IOException {
+        if (this.javaRebelPath != null) {
+            final String canonicalJavaRebelPath =
+                this.javaRebelPath.getCanonicalPath();
+            if (this.javaRebelPath.exists()) {
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: on one line

File: src/main/java/scala_maven/ScalaConsoleMojo.java [hunk 7]
```diff
@@ -55,50 +75,263 @@
...
-        if (useRuntimeClasspath) {
-            classpath.addAll(project.getRuntimeClasspathElements());
+        // Force no forking
+        final JavaMainCaller jcmd =
+            super.getScalaCommand(false,
+                                  this.mainConsole);
+        // Determine Scala Version
+        final VersionNumber scalaVersion =
+            super.findScalaVersion();
+        final Set<String> classpath =
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: on one line

File: src/main/java/scala_maven/ScalaMojoSupport.java [hunk 8]
```diff
@@ -373,47 +386,137 @@ public String getScalaOrganization(){
...
+     *         ArtifactResolver}.
+     */
+    private ArtifactResolutionRequest createArtifactResolutionRequest(final Artifact artifact,
+                                                                      final ArtifactFilter collectionFilter,
+                                                                      final ArtifactFilter resolutionFilter,
+                                                                      final List<ArtifactRepository> remoteRepositories,
+                                                                      final ArtifactRepository localRepository) {
+        final ArtifactResolutionRequest arr =
+            new ArtifactResolutionRequest();
+
```
Comment (davidB) [inline src/main/java/scala_maven/ScalaMojoSupport.java]: on one line

File: src/main/java/scala_maven/ScalaConsoleMojo.java (hunk 1 above)
Comment (isomarcte) [inline src/main/java/scala_maven/ScalaConsoleMojo.java]: Will do. It is a personal preference of mine to have fully expanded branches, but I recognize that is a subjective point of view.

**Comment by isomarcte** [comment]
@davidB Requested updates made. Would you be amiable to us adding CheckStyle for such things?

**Comment by hakujin** [comment]
Hi, anything I can do to help this PR get merged? The title is unintentionally misleading: this bug affects every scala version > `2.11.8`.

**Comment by davidB** [comment]
I just need time to review, check, release,...

Sorry

**Comment by isomarcte** [comment]
@davidB anything I can do to move this along?

**Comment by sword865** [comment]
really like this, hope this fix can be merged. anything I can help?

**Comment by davidB** [comment]
Big thanks, I'll deploy the release later this week. (I would like to do some other minor change)
